Add support for GLN and GLN Extension.
DacoTaco/BarcodeParserBuilder pull request #18
Opened 2024-03-27 20:39 UTC by marydeshon

Add support for GLN and GLN Extension.

Fixes DacoTaco/BarcodeParserBuilder#17

2024-03-31 08:17 UTC, DacoTaco requested changes

2024-03-31 08:17 UTC, DacoTaco commented on BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs
can't you add these test cases to the existing testcase functions? that way they are also run for GS128 barcodes and in the general barcode tests

2024-04-03 16:19 UTC, DacoTaco commented on BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs
sorry if it wasn't clear. what i meant is that there is already a test function & member data containing par'sable test cases (https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs#L230-L479) and the test function already checks some fields (https://github.com/DacoTaco/BarcodeParserBuilder/blob/main/BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs#L43-L63)

it might be beneficial to add the test cases & asserts to those places instead of making new functions instead

2024-04-04 20:26 UTC, marydeshon commented on BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs
Ok thank you for the clarification. I did move the test cases to where they belonged.
I did notice an oddity while testing.
CanBuildBarcodes is seemingly dependent on the order of the AIs within the barcode string.
Not sure if this is expected behaviour.
```CanBuildBarcodes is seemingly dependent on the order of the AIs within the barcode string.

This works:

            //SerialNumber
            {
                $"0134567890123457103456789{GroupSeparator}213456789-012",
                new GS1Barcode()
                {
                    ProductCode = TestProductCode.CreateProductCode<GtinProductCode>("34567890123457", (productCode) =>
                    {
                        productCode.Type = ProductCodeType.GTIN;
                        productCode.Value = "456789012345";
                        productCode.Indicator = 3;
                    }),
                    BatchNumber = "3456789",
                    SerialNumber = "3456789-012"
                }
            },


This does not:
            //SerialNumber
            {
                $"0134567890123457213456789-012{GroupSeparator}103456789",
                new GS1Barcode()
                {
                    ProductCode = TestProductCode.CreateProductCode<GtinProductCode>("34567890123457", (productCode) =>
                    {
                        productCode.Type = ProductCodeType.GTIN;
                        productCode.Value = "456789012345";
                        productCode.Indicator = 3;
                    }),
                    BatchNumber = "3456789",
                    SerialNumber = "3456789-012"
                }
            },

2024-04-04 21:00 UTC, DacoTaco commented on BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs
ye, that would be correct. the building follows the fields by number, and the string should as well otherwise the strings will be different. looks good to me!

2024-04-04 21:00 UTC, DacoTaco approved these changes

2024-04-04 21:00 UTC, merged

2024-04-04 21:04 UTC, marydeshon commented on BarcodeParserBuilder.UnitTests/Barcodes/GS1/GS1BarcodeParserBuilderTestFixture.cs
Thank you!